"""Acknowledge status added in incidents table enum

Revision ID: a2251bf239fe
Revises: cfdad1797ac4
Create Date: 2026-06-25 14:10:24.213651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2251bf239fe'
down_revision: Union[str, Sequence[str], None] = 'cfdad1797ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alerts_incident_id_fkey'), 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'incidents', ['incident_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("sdffdsdf", 'alerts', type_='foreignkey')
    op.create_foreign_key(op.f('alerts_incident_id_fkey'), 'alerts', 'incidents', ['incident_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
