"""add_cascade_delete_to_incidents_table

Revision ID: cfdad1797ac4
Revises: 
Create Date: 2026-06-25 03:46:54.862046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdad1797ac4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('incident_events_incident_id_fkey'), 'incident_events', type_='foreignkey')
    op.create_foreign_key(None, 'incident_events', 'incidents', ['incident_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('incident_foreign_key_without_cascade', 'incident_events', type_='foreignkey')
    op.create_foreign_key(op.f('incident_events_incident_id_fkey'), 'incident_events', 'incidents', ['incident_id'], ['id'])
    # ### end Alembic commands ###
